config/routes.rb
EventTracker::Application.routes.draw do
   resources :events do
     resources :participants do
      member do
        post :add_guest
      end
    end
   end
root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :location, :name
  has_many :participants
  def total_participants
    total = self.participants.count
    self.participants.each do |participant|
      total += participant.guests
    end
    return total
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :event_id, :guests, :name
  belongs_to :event
   def popularity_label
    if guests < 2
      ""
    elsif guests < 5
      "Friendly"
    elsif guests < 10
      "Popular"
    elsif guests < 25
      "Social Butterfly"
    else
      "Pop Icon"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
   @events = Event.all
  end
   def new
    @event = Event.new
  end
 
  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to events_url
    else
      render action: "new"
    end
  end
   def edit
    @event = Event.find(params[:id])
  end
 
  def update
    @event = Event.find(params[:id])
 
    if @event.update_attributes(params[:event])
      redirect_to events_path
    else
      render action: "edit"
    end
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
    def create
      @event = Event.find(params[:event_id])
      @participant = @event.participants.new(params[:participant])
      if @participant.save
        redirect_to event_url(@event)
      else
        redirect_to event_url(@event)
      end
    end
    def add_guest
      @event = Event.find(params[:event_id])
      @participant = Participant.find(params[:id])
      @participant.guests += 1
      @participant.save
      redirect_to event_url(@event)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/events/edit.html.erb
<h2>Edit <%= @event.name %></h2>
 
<%= form_for @event do |form| %>
  <div>
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>
 
  <div>
    <%= form.label :description %><br />
    <%= form.text_field :description %>
  </div>
 
  <div>
    <%= form.label :location %><br />
    <%= form.text_field :location %>
  </div>
 
  <p><%= form.submit %></p>
<% end %>

app/views/events/index.html.erb
<div class="hero-unit">
  <h1>Event Tracker</h1>
  <p>Planning an event? Track the participants here!</p>
  <p><%= link_to "Create New Event", new_event_url, :class => "brn btn-primary btn-large" %></p>
</div>
 
<table class="table table-striped">
  <thead> 
    <th>Event</th>
     <th>Total Participants</th>
    <th>Actions</td>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td>
          <%= link_to event.name, event_path(event) %> - <%= event.description %><br />
          <%= event.location %>
        </td>
         <td><%= event.total_participants %></td>
        <td>
          <%= link_to "Edit", edit_event_path(event) %>
          <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody> 
</table>
  

app/views/events/new.html.erb
<h2>Create New Event</h2>
<%= form_for @event do |form| %>
  <div>
    <%= form.label :name %><br />
    <%= form.text_field :name %>
  </div>
 
  <div>
    <%= form.label :description %><br />
    <%= form.text_field :description %>
  </div>
 
  <div>
    <%= form.label :location %><br />
    <%= form.text_field :location %>
  </div>
 
  <p><%= form.submit %></p>
<% end %>

app/views/events/show.html.erb
<div class="hero-unit">
<h2><%= @event.name %></h2>
<h3><%= @event.description %></h3>
<p><%= @event.location %></p>
  </div>
<h3>Participants</h3>
<ul>
<% @event.participants.each do |single_participant| %>
   <li><%= single_participant.name %> is bringing <%= single_participant.guests %> guests<br />
      <li><strong><%= single_participant.popularity_label %></strong> <%= single_participant.name %> is bringing <%= single_participant.guests %> guests<br />
    Bringing a guest?  <%= button_to "Guest +1", add_guest_event_participant_path(@event.id, single_participant.id) %>
  </li>
<% end %>
</ul>
<h2>Add Participant</h2>
 
<%= form_for [@event, @event.participants.new]  do |form| %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EventTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container">
<%= yield %>
</div>
</body>
</html>